# Calculator for matrix 1 row or victor

In [1]:
import numpy as np


def calcuator():
    while True:
        print("Welcome to our super calcuator please chose ur mathmatical operation : ")
   
        print("1/ Addition")
    
        print("2/ Subtraction")
      
        print("3/ Multiplication")
    
        print("4/ Division")

        operation = int(input("Enter the number of the operation :"))

        if(operation == 1):
            n0 = np.array(eval(input("Enter a first matrix plz: ")))
            n1 = np.array(eval(input("Enter a second matrix plz: ")))
            result = n0 + n1
            print(result)
            break
        elif(operation == 2):
            n0 = np.array(eval(input("Enter a first matrix plz: ")))
            n1 = np.array(eval(input("Enter a second matrix plz: ")))
            result = n0 - n1
            print(result)
            break
        elif(operation == 3):
            n0 = np.array(eval(input("Enter a first matrix plz: ")))
            n1 = np.array(eval(input("Enter a second matrix plz: ")))
            result = n0 * n1
            print(result)
            break
        elif(operation == 4):
            n0 = np.array(eval(input("Enter a first matrix plz: ")))
            n1 = np.array(eval(input("Enter a second matrix plz: ")))
            result = n0 / n1
            print(result)
            break
        else:
            print("Invalid operation try again")   
            
            

calcuator()

Welcome to our super calcuator please chose ur mathmatical operation : 
1/ Addition
2/ Subtraction
3/ Multiplication
4/ Division
[20 40 60]


# Operations for Victor and Matrix

In [2]:
import numpy as np

In [3]:
# Victor

v1 = np.array([10, 20, 30])
v2 = np.array([40, 50, 60])

vt1 = v1 + v2
print(vt1)

vt2 = v1 - v2
print(vt2)

vt3 = v1 * v2
print(vt3)

vt4 = v1 / v2
print(vt4)


[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]


In [6]:
#Matrix

m1 = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

m2 = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

mt1 = m1 + m2
print(mt1)

print("----------")

mt2 = m1 - m2
print(mt2)

print("----------")

mt3 = m1 * m2
print(mt3)

print("----------")

mt4 = m1 / m2
print(mt4)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
----------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
----------
[[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]
----------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
me = np.linalg.eig(m1)

me

EigResult(eigenvalues=array([ 1.61168440e+02, -1.11684397e+01,  2.06802688e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))